### PR TITLE
Tune scale kernel in BifrostTuner

### PR DESCRIPTION
**Pull request by Chunosov**

### CODE REVIEW

**Comment by psyhtest** [comment]
Here's a summary of execution time improvements at 178 MHz:

resizebilinear

(Pairs of bars represent "before" and "after" the optimisation for a range of tensor shapes.)

**Comment by psyhtest** [comment]
Speedups range from 1.1x:
resizebilinear_1 1x

to 1.5x:
resizebilinear_1 5x

**Comment by GeorgeARM** [comment]
Cherry picked. Will be part of the next release.

**Comment by mdigiorgio** [comment]
This change is now part of the v18.08 release. Thanks for your contribution.

**Pull request closed without merging**
