### PR TITLE
ReQuEST direct convolution kernel

### PR DESCRIPTION
**Pull request by psyhtest**
This PR provides a new direct convolution kernel which we used for [dividiti's submission](https://github.com/dividiti/ck-request-asplos18-mobilenets-armcl-opencl) to the [1st ReQuEST competition at ASPLOS'18](http://cknowledge.org/request-cfp-asplos2018.html).

As I will prove shortly, this kernel is faster than GEMM-based convolution for 15 out of 16 MobileNets models (i.e. all except the baseline model with the width multiplier of 1.0 and the resolution of `224x224`).

### CODE REVIEW

**Comment by psyhtest** [comment]
Here's how to read the graph:
- The colour of a marker denotes the version of ArmCL: "17.12", "18.01", "18.03", "dv/dt" (this PR from a fork of "18.03").
- The size of a marker is proportional to the input resolution: 224 (the largest), 192, 160, 128 (the smallest).
- The shape of a marker denotes both the channel multiplier and the convolution method:
  - Direct convolution: 1.00 - pentagon, 0.75 - square, 0.50 - triangle-up, 0.25 - circle.
  - GEMM-based convolution: 1.00 - star, 0.75 - diamond, 0.50 - triangle-down, 0.25 - octagon.

Roughly speaking, a shape has **N** corners for the channel multiplier of **(N-1)*0.25**:
- 5 corners for the channel multiplier of 1.0 (pentagon or star);
- 4 corners for the channel multiplier of 0.75 (square or diamond);
- 3 corners for the channel multiplier of 0.50 (triangle-up or triangle-down); 
- "no corners" for the channel multiplier of 0.25 (circle or octagon).

**Comment by psyhtest** [comment]
The plot bounds are chosen so that all the 32 points for ArmCL 18.03 are shown (32 = 4 input resolutions times 4 channel multiplies times 2 convolution methods). Only a few points are shown for ArmCL 17.12 for two reasons:
1. dividiti's optimisations for direct convolution kernels were mostly disabled in 17.12 due to bugs (https://github.com/ARM-software/ComputeLibrary/issues/322, https://github.com/ARM-software/ComputeLibrary/issues/323), which were fixed in 18.01. Therefore, the most accurate points were simply too slow with 17.12 (> 100 ms).
2. For some points, accuracy dropped practically to ~10%. Presumably, this was due to some other bug in 17.12 which also got fixed in 18.01.

**Comment by psyhtest** [comment]
This graph plots Top 1 accuracy on all the 50,000 images of the ImageNet validation set (Y, %) against the image classification time (X, ms). Due to the long evaluation time across all the 16 models, accuracy was only evaluated using ArmCL 18.03, and then reused for the other library variants (therefore, no accuracy degradation for ArmCL 17.12 described above is visible).

accuracy_top1_ 50000 dv_dt 18_03 18_01 17_12

**Comment by psyhtest** [comment]
In summary, using direct convolution is faster than GEMM-based convolution for 15 MobileNets models out of 16 (i.e., all except the baseline model with the channel multiplier of 1.00 and input resolution of 224). Also, it's practically possible to exceed AlexNet-level accuracy (0.59 > 0.57) in only about 17 ms per image.

**Comment by AnthonyARM** [comment]
FYI: We haven't forgotten about you but we're a bit tight for the merge window for 18.05, so I moved this PR to 18.08

**Comment by psyhtest** [comment]
@AnthonyARM I am looking at resolving the conflict. But I don't see the code for setting the local work size hint (`_lws_hint`) any more. Do you completely rely on online tuning now please?

**Comment by psyhtest** [comment]
OK, I've found it [here](https://github.com/ARM-software/ComputeLibrary/blob/master/src/runtime/CL/tuners/BifrostTuner.cpp).

Now, we have heuristics to submit for setting up `_lws_hint` for a couple of other kernels. Would you suggest to place them similarly to this file?

**Comment by AnthonyARM** [comment]
@psyhtest Yes, that's correct, we're going to move all the heuristics to that file.

We've also got a ticket to look at this PR which is getting near the top of our backlog now.

**Comment by psyhtest** [comment]
Thanks @AnthonyARM. We've clearly been unlucky with direct convolution being moved there first :). Perhaps it will be easier to merge it on your side then. The heuristics are still the same.

**Comment by GeorgeARM** [comment]
I tried to merge this pull request and found out that is >1.5x slower in both dynamic and static tuning against the gemm approach for the two mobilenet graph examples that we support in benchmarks. Can you rebase and check against 18.05?

**Comment by psyhtest** [comment]
Hi @GeorgeARM, As the above graph shows, this kernel is indeed slower for the baseline version (although not > 1.5x slower). I'll check against v18.05 in 1-2 weeks.

I suspect the reason it is slower relates to your second comment. This **used** to be correct in v17.12-v18.03 (https://github.com/ARM-software/ComputeLibrary/blob/c3f34a43ffb5d52ee4a4e9f7b1bf4c6c002aeebb/src/core/CL/kernels/CLDirectConvolutionLayerKernel.cpp#L331), but is now broken in v18.05 (https://github.com/ARM-software/ComputeLibrary/blob/b3a371bc429d2ba45e56baaf239d8200c2662a74/src/runtime/CL/tuners/BifrostTuner.cpp#L68).

The trailing underscore there was intentional - to signal that it was "sort of product of input dimensions" but not quite (please read the comment above).

**Comment by GeorgeARM** [comment]
Closing this pull request as no performance benefit has been noted in latest ACL.
Reopen if needed. Thank you

**Comment by psyhtest** [comment]
On your request, I have provided further evidence on the performance our ReQuEST kernel :). Unfortunately, I do not seem to have permissions to re-open this pull request? ("request" again!:))

**Pull request closed without merging**
